name: data_analysis_iseg
channels:
  - conda-forge
dependencies:
  - r-base
  - r-irkernel
  - r-tidyverse
  - r-essentials
  - notebook
  - jupyterlab
  - ipykernel
  - r-readr
  - r-readxl
  - ipywidgets
  - r-readr
  - r-readxl
  - r-repr
  - lckr_jupyterlab_variableinspector
