name: data_analysis_iseg
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-irkernel
  - r-tidyverse
  - r-essentials
  - notebook
  - jupyterlab
  - ipykernel
  - ipywidgets
  - r-readr
  - r-readxl
  - r-repr
  - r-mnort
  - r-psych
  - lckr_jupyterlab_variableinspector
  - r-devtools
  - r-jsonlite
  - r-knitr
  - r-ggplot2
  - r-clipr
  - r-desctools
  - r-ineq
