install.packages("readr")
install.packages("tidyverse")
install.packages("IRkernel")
IRkernel::installspec()
install.packages("readxl")
install.packages("repr")
install.packages("dplyr")
install.packages("knitr")
install.packages("psych")
install.packages("clipr")
install.packages("DescTools") 
install.packages("ineq") 
install.packages("ggplot2")

 
