install.packages("rlang", repos = "https://cloud.r-project.org")
install.packages("tidyverse")
install.packages("IRkernel")
install.packages("readxl")
install.packages("rlang", repos = "https://cloud.r-project.org")
install.packages("dplyr", repos = "https://cloud.r-project.org")
install.packages("readr", repos = "https://cloud.r-project.org")
install.packages("readxl", repos = "https://cloud.r-project.org")
install.packages("knitr", repos = "https://cloud.r-project.org")
install.packages("ggplot2", repos = "https://cloud.r-project.org")
install.packages("clipr", repos = "https://cloud.r-project.org")
install.packages("DescTools", repos = "https://cloud.r-project.org")
install.packages("ineq", repos = "https://cloud.r-project.org")
install.packages("mnormt")
install.packages("libyaml")
install.packages("psych", binary=TRUE, dependencies=TRUE)
