#!/bin/bash
set -ex

# Upgrade pip and install Python tools
pip install --upgrade pip

# Install for both classic Jupyter Notebook and JupyterLab
pip install nbgitpuller ipywidgets lckr_jupyterlab_variableinspector 
pip install jupyter_contrib_nbextensions

# Enable ipywidgets in classic notebook
jupyter nbextension enable --py widgetsnbextension --sys-prefix

# Enable classic notebook extensions
jupyter contrib nbextension install --sys-prefix
jupyter nbextension enable varInspector/main

